### ISSUE TITLE
Dropdown content is not positioned correctly when paper-dropdown-menu is inside an iron-list

### ISSUE THREAD

**Issue by bpinney** [PolymerElements/paper-dropdown-menu#101]
Here is a JSbin of paper-dropdown-menu items in a dom-repeat, reflecting the expected outcome of working great and dropdown content appearing next to the paper-menu-item: http://jsbin.com/nizeta/edit?html,output

Here is a JSbin of paper-dropdown-menu items in an iron-list, reflecting the not so great actual behavior, the dropdown content appearing at position other than that of it's parent: http://jsbin.com/heqike/edit?html,output

There appear to be other visual issues as well, but the issue in the title is my primary concern.

**Comment by arno-london** [comment]
Any plan to fix the problem?

It is impossible to use the paper-dropdown-menu inside an iron-list. The dropdown is not displayed in my case. There is another problem inside a paper-dialog, some parts of the dialog are removed when the paper-dropdown-menu is clicked.

**Comment by bpinney** [comment]
This issue is being tracked elsewhere. @cdata:

> Please follow PolymerElements/iron-fit-behavior#33 as the canonical tracking issue for this problem. Closing this one.
