### ISSUE TITLE
On FF, a disabled menu with a selected item looks wonky

### ISSUE THREAD

**Issue by notwaldorf** [PolymerElements/paper-dropdown-menu#106]
Repro steps: http://jsbin.com/jekupi/edit?html,output
Wonky:
<img width="246" alt="screen shot 2015-12-14 at 7 26 46 pm" src="https://cloud.githubusercontent.com/assets/1369170/11801212/a1dc373c-a298-11e5-8752-c2cafff83e74.png">

**Comment by bicknellr** [comment]
I've been looking into this for a bit and Firefox is dropping a change event in iron-input. If you put a debugger before [this line](https://github.com/PolymerElements/iron-input/blob/72169bec94949ed81d6e8d0f81413d68b1122047/iron-input.html#L132), `bind-value-changed` gets fired twice - first during `_ready` and second as a result of the iron-selector setting its initial selected value. The first time, everything seems fine, but in the second call to fire, `node.dispatchEvent(event)` does nothing. The event isn't cancelable yet neither of the event handlers for `bind-value-changed` are called (including the one which propagates this back up to the paper-input, affecting the label).

In the middle of writing that I finally decided to look at the iron-input bugs and this is totally a dup of PolymerElements/iron-input#47, so PolymerElements/iron-input#69 is probably going to fix this. And, what do you know, `this.hasAttribute('disabled')` returns false during the first firing of `bind-value-changed` and true the next.. I'll take this as a lesson to do more digging first..

**Comment by notwaldorf** [comment]
Yeah, this is happening because `dispatchEvent` is hosed on FF for disabled items. https://github.com/PolymerElements/iron-input/pull/69 will fix that.

**Comment by valdrinkoshi** [comment]
This has been fixed with `iron-input v1.0.8` 🎉 
<img width="232" alt="screen shot 2016-06-30 at 1 09 55 am" src="https://cloud.githubusercontent.com/assets/6173664/16471884/3c138040-3e60-11e6-87dd-1bfaf3d1d343.png">

**Comment by notwaldorf** [comment]
I think we can just close it. We don't need to update the `bower`, i don't think, since we're not using a feature that didn't exist before 1.0.8 -- it just worked poorly before it.
