### ISSUE TITLE
Can't select from the list

### ISSUE THREAD

**Issue by m0b0u0** [PolymerElements/paper-dropdown-menu#11]
I installed  the latest Iron, Paper and Neon components plus the paper-dropdown-menu over it, then tried it with the supplied example. 

- The dropdown element shows up...
- ...the menu shows up when I click on the dropdown...
- ...but can't make a selection from the list: the hand pointer shows over the list but nothing happens when I click to select from the list.

Chrome 44.0.2403.130 m on Windows 10. 
Same issue on Firefox.

**Comment by cdata** [comment]
Hi, can you please supply a reduced test case and re-open this issue? Thanks!

Here is a link to our [contributor guidelines](https://github.com/PolymerElements/paper-dropdown-menu/blob/master/CONTRIBUTING.md) in case you need more detail.
