### ISSUE TITLE
Demo paths broken

### ISSUE THREAD

**Issue by freshp86** [PolymerElements/paper-dropdown-menu#115]
Repro steps
1) Clone paper-dropdown-menu repo
2) bower install
3) Start a local webserver
4) Navigate to http://localhost:8888/demo/index.html

This results in a bunch of network errors, because the paths in demo/index.html are wrong, for example
```
<script src="../../webcomponentsjs/webcomponents-lite.js"></script>
```
should be changed to
```
<script src="../bower_components/webcomponentsjs/webcomponents-lite.js"></script>
```

Should I send a pull request, or is there another reason the paths are using `../..`?

**Comment by cdata** [comment]
These paths are written correctly for distribution purposes. When this project is installed as a `bower` dependency of another project, the paths are correct. For development, we use a special server called Polyserve to correct the paths. Please check out Polyserve here: https://github.com/PolymerLabs/polyserve.
