### ISSUE TITLE
No option to render the menu below the click target

### ISSUE THREAD

**Issue by freshp86** [PolymerElements/paper-dropdown-menu#117]
Trying to achieve this http://imgur.com/6UhlgT5. In all examples the dropdown menu is obscuring the click target to open the menu and I could not find an option to change this.

**Comment by MeTaNoV** [comment]
dup of https://github.com/PolymerElements/paper-dropdown-menu/issues/98

**Comment by valdrinkoshi** [comment]
Will close this & continue the discussion on #98
