### ISSUE TITLE
shift-tabbing past disabled dropdown menu

### ISSUE THREAD

**Issue by nalbion** [PolymerElements/paper-dropdown-menu#121]
In the demo, if you focus on the last dropdown-menu (on a browser with height of, say, 500px) and press shift-tab to navigate back through the other dropdown-menus, the view scrolls to show the focused menu - until you reach the disabled menu, then there is no more scrolling for subsequent shift-tabs.

**Comment by cdata** [comment]
Hi, I can't seem to reproduce the described problem on our released demo page. Please re-open this issue if it still occurs, with a JSBin containing a set of reproducible steps! For more details on filing issues, please refer to our [contributing guidelines](../blob/master/CONTRIBUTING.md).
