### ISSUE TITLE
Why does this component have a ripple effect?

### ISSUE THREAD

**Issue by miztroh** [PolymerElements/paper-dropdown-menu#13]
I see that this component has a ripple effect and that this is the behavior shown in the Material Design spec.  My question is this: Since this component is based on paper-input and paper-input no longer has a ripple, why does paper-dropdown-menu have a ripple?

https://www.google.com/design/spec/components/menus.html#menus-usage

**Comment by cdata** [comment]
It is not a direct derivative of `paper-input`. Also, according to video in the spec, this element is intended to have a ripple effect: https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B6Okdz75tqQsUWtQaDc0MnJOUmc/Components-Menus-Usage-Textfield_Dropdown_xhdpi_006.webm
