### ISSUE TITLE
Dropdowns shift after expanding

### ISSUE THREAD

**Issue by progers** [PolymerElements/paper-dropdown-menu#134]
On the paper dropdown demo, the dropdowns will move around after they have expanded. This is different from #130 where the scrollbar disappears, as it's the actual popup that's moving. This may be related to non-overlay scrollbars which are the default when a mouse is plugged in.

I've attached an exciting movie showing this behavior.
[jumpydropdowns.zip](https://github.com/PolymerElements/paper-dropdown-menu/files/150507/jumpydropdowns.zip)

**Comment by jahglow** [comment]
I believe it readjust itself to match the position of the container which shifts when scrollbars disappear

**Comment by ebidel** [comment]
Seeing this too for the IO sight. Every use of paper-dropdown-menu is doing this. The most violent is our top nav:

![screenflow](https://cloud.githubusercontent.com/assets/238208/13761259/b607b30a-e9f4-11e5-931e-f7cfa5fb9cb6.gif)

cc @cdata @notwaldorf

**Comment by miztroh** [comment]
+1

**Comment by jahglow** [comment]
If animation is disabled then there is no shift

вт, 15 марта 2016, 1:00 Jonathan Cox <notifications@github.com>:

**Comment by valdrinkoshi** [comment]
Looks very similar to https://github.com/PolymerElements/iron-dropdown/issues/69

Do you guys have `iron-dropdown v 1.3.0`?

**Comment by ebidel** [comment]
Pulled down the latest releases and it seems to be gone!

**Comment by valdrinkoshi** [comment]
yay! closing this.
@progers @miztroh LMK if this is still an issue for you, and I'll reopen again ;)

**Comment by miztroh** [comment]
@valdrinkoshi Looks good to me too.  Thanks!
