### ISSUE TITLE
background jump around after click outside the menu

### ISSUE THREAD

**Issue by linghuaj** [PolymerElements/paper-dropdown-menu#135]
When i click on the input, a menu shows up. Whole background moves towards right under the menu, (and scrollbar disappears). 

When I click outside of the menu, it jumped back. 

Feels weird.  Is this by design?

Here is a screenshot
https://gist.github.com/linghuaj/2cfe9c384eb1318de226

**Comment by WoodyWoodsta** [comment]
Dupe: https://github.com/PolymerElements/paper-dropdown-menu/issues/130
