### ISSUE TITLE
Misalignment of a dropdown agains the trigger 

### ISSUE THREAD

**Issue by jahglow** [PolymerElements/paper-dropdown-menu#136]
If right-aligned, the dropdown paper-sheet overlaying the control goes somewhat 50px to the right of the control, thus isn't aligned to the right edge. See demo in the docs

**Comment by valdrinkoshi** [comment]
Demo looks fine, correctly aligned to the right edge
![demo-looks-fine](https://cloud.githubusercontent.com/assets/6173664/16524971/78736b5e-3faa-11e6-8645-36b8f295991f.gif)

Closing this, will reopen if the problem persists (please provide a jsbin or code snippet to expose the issue)
