### ISSUE TITLE
Not possible to use in a webform

### ISSUE THREAD

**Issue by 34code** [PolymerElements/paper-dropdown-menu#139]
### Description
paper-dropdown-menu cannot be used in a web form even if it is an iron-form. The "value" of the paper-items are not exposed to the form.

### Expected outcome

paper-dropdown-menu should be able to replace select fields in forms

### Actual outcome

Unable to POST selected value in paper dropdown menu back to the server

### Live Demo
N/A

### Steps to reproduce

1. Put a `paper-dropdown-menu` element in the page within a form.
2. Open the page in a web browser.
3. Select an item within paper-dropdown-menu
4. Submit the form

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by valdrinkoshi** [comment]
It requires your form to be an `iron-form`, and it will work as expected http://jsbin.com/boyege/1/edit?html,console,output
(I've logged also the `form.serialize()` but that's not necessary)
<img width="696" alt="screen shot 2016-07-01 at 12 23 09 am" src="https://cloud.githubusercontent.com/assets/6173664/16506386/3f0f0c70-3f22-11e6-967c-08ba40012846.png">

Closing this, let me know if the problem persists (a jsbin would be helpful), and I'll reopen this ;)
