### ISSUE TITLE
Mixin is not being applied paper-input-container-input

### ISSUE THREAD

**Issue by victorhugom** [PolymerElements/paper-dropdown-menu#140]
### Description

The mixin `--paper-input-container-input` is not being applied to the  `paper-dropdown-menu` element

### Expected outcome

The components does not changes

### Actual outcome

According to the docs the  `paper-dropdown-menu` accepts all `paper-input-container` style

### Steps to reproduce

1. Put a `paper-dropdown-menu` inside another element.
2. Create a mixin
 ex:
``` :root {
  --paper-input-container-input: {
          border: 1px solid #e5e5e5;
          padding: 10px 0 5px 10px;
      }
}```

### Browsers Affected
<!-- Check all that apply -->
- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [x] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by valdrinkoshi** [comment]
You need to apply the mixin to the `paper-dropdown-menu` for it to work, see here http://jsbin.com/bubecuh/1/edit?html,output

Closing this, please let me know if the problem persists and I'll reopen this

**Comment by ankitsinghal0880** [comment]
Hi , Need some help. I have a requirement to display paper-dropdown-menu as a standard dropdown and not in material design. I need to do it through stylesheet as few of our customer still want to have old look/feel and we do not want to have custom coding instead  trying to change the look/feel using styles. I am able to display paper-input like legacy elements easily by using paper-input-container styles but no luck with dropdown. Any suggestions that y'all may have.
