### ISSUE TITLE
paper-dropdown-menu-light style differences

### ISSUE THREAD

**Issue by mgiuffrida** [PolymerElements/paper-dropdown-menu#143]
I'm seeing some differences between paper-dropdown-menu and paper-dropdown-menu-light. They have different widths in flex layouts:

https://jsfiddle.net/mgiuffrida/30wysv8m/

There's also a padding/clipping issue I can't repro easily, but it has something to do with the `padding-top: 0` applied to the `div#input` when `no-label-float` is present.

**Comment by notwaldorf** [comment]
Eeeek, on it. Though, from your demo, the original `paper-dropdown-menu` loses its dropdown in a flex layout, so that wasn't doing too great to begin with 😟
