### ISSUE TITLE
Error When using vulcanized import

### ISSUE THREAD

**Issue by bkr32** [PolymerElements/paper-dropdown-menu#149]
when using a vulcanized  import file i get the following error when trying to click the drop down menu 

Uncaught ReferenceError: KeyframeEffect is not defined

it works fine when using normal import method

**Comment by valdrinkoshi** [comment]
This might have been related to https://github.com/PolymerElements/paper-menu-button/issues/16 which has been fixed in `paper-menu-button v1.1.2`. @bkr32 could you please check if that is the case or if the problem persists?

**Comment by bkr32** [comment]
it appears to be fixed now 
thanks
