### ISSUE TITLE
Long delay between paper-dropdown-menu open and focus

### ISSUE THREAD

**Issue by rictic** [PolymerElements/paper-dropdown-menu#150]
Moved from internal bug:

See: https://elements.polymer-project.org/elements/paper-dropdown-menu?view=demo:demo/index.html&active=paper-dropdown-menu

In paper-dropdown-menu I'm seeing a 540ms delay between when the dropdown is opened and the first item gets rendered as focused. This creates a jarring change after the UI should already be stable.

This is caused by focus being applied in `iron-overlay-behavior`'s `_finishRenderOpened`. If focus causes visual changes then it should be applied before the open animation.

Alternatively the style for the focus should be much less glaring.

```css
paper-menu {
  --paper-menu-focused-item: {
    display: none;
  };
}
```

**Comment by valdrinkoshi** [comment]
This is a behavior of `iron-overlay-behavior`, which postpones the focusing at the end of the animations. This should be done before. Will move this issue there

**Comment by valdrinkoshi** [comment]
This issue was moved to PolymerElements/iron-overlay-behavior#201
