### ISSUE TITLE
Menu within a dialog should not change focus when closing

### ISSUE THREAD

**Issue by rictic** [PolymerElements/paper-dropdown-menu#151]
Moved from an issue that was filed internally:

- Have a dialog containing a menu
- Open a dropdown menu within the dialog
- Dismiss menu by clicking on a focusable element within the dialog (such as an input element)

Observed:
input element is initially correctly focused, but 1/2 second later the focus is moved to the dropdown menu. This is because when the dropdown menu finishes its closing animation it calls `Polymer.IronOverlayBehaviorImpl._applyFocus.apply(this, arguments);` This shifts the focused element inside the dialog.

**Comment by valdrinkoshi** [comment]
This has been fixed since overlays now keep track of what's the focused child, and restore the focus there (in your example, on the input)
https://jsbin.com/laforaz/3/edit?html,output
