### ISSUE TITLE
underline mixins may need tweaking (have to override 2 in order to hide underline)

### ISSUE THREAD

**Issue by ktiedt** [PolymerElements/paper-dropdown-menu#155]
### Description

In the demo it explains how to remove the underline from a paper-dropdown-menu however it doesnt work because `--paper-inout-container-underline-focus` is also not overridden, as seen here: https://github.com/PolymerElements/paper-dropdown-menu/blob/master/demo/index.html#L218-L221
### Expected outcome
Would not expect to have to override both `--paper-input-container-underline` and `--paper-input-container-underline-focus` to hide the underline

### Actual outcome
underline appears when you click the paper-dropdown-menu that is said to have no underline.

### Live Demo

https://elements.polymer-project.org/elements/paper-dropdown-menu?active=paper-dropdown-menu&view=demo:demo/index.html

**Comment by valdrinkoshi** [comment]
Will move this issue to `paper-input`, as those are mixins of `paper-input`

**Comment by valdrinkoshi** [comment]
This issue was moved to PolymerElements/paper-input#405
