### ISSUE TITLE
Dropdown with 1 element in the list won't select if selected or default

### ISSUE THREAD

**Issue by ljgww** [PolymerElements/paper-dropdown-menu#157]
### Description

Dropdown with 1 element in the list wont select the item if item is already selected or default selection is predefined in the code

### Expected outcome

Closing the popup list

### Actual outcome

Popup list stays

### Steps to reproduce

    <paper-dropdown-menu label="one?">
      <paper-listbox  class="dropdown-content"   attr-for-selected="value" selected="default" >
         <paper-item value="default">One with Default selection</paper-item>
      </paper-listbox>
    </paper-dropdown-menu>							

    <paper-dropdown-menu label="one no default?">
       <paper-listbox  class="dropdown-content"  >
           <paper-item value="default">One no Default selection</paper-item>
       </paper-listbox>
    </paper-dropdown-menu>

- click on dropdowns in attempt to select
- if predefined no default selection selection can be made, but only until it is selected
- selection not closing (need to click outside)

### Browsers Affected

- [ x ] Chrome / NWjs / windows 7
- [ x ] Firefox / windows 7
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ x ] IE 11 / windows 7
- [ ] IE 10

**Comment by Stefdv** [comment]
Yes...that's a problem for me too

**Comment by bicknellr** [comment]
As a workaround, you can listen for `iron-activate` and check the selection state + close the menu when that happens. [Here's a demo.](http://jsbin.com/gedemu/1/edit?html,output)

**Comment by valdrinkoshi** [comment]
You can also listen to `tap` event on the `paper-listbox` and close the menu http://jsbin.com/fasagi/1/edit?html,output
Anyways this issue doesn't belong here, it should go to `paper-menu-button` as it is the one controlling the close on selection change, so I'll move it there. 
I believe the current behavior is by design, a selection change should close the dropdown.

**Comment by valdrinkoshi** [comment]
This issue was moved to PolymerElements/paper-menu-button#85
