### ISSUE TITLE
--paper-dropdown-menu-input mixin not working

### ISSUE THREAD

**Issue by azumbrunnen** [PolymerElements/paper-dropdown-menu#18]
When trying to set font-size of the paper-dropdown-menu component, the mixin fails:

`
--paper-dropdown-menu-input: {
font-size: 13px;
}
`

**Comment by benjyblack** [comment]
Same issue... It sets the `font-size` properly on the `<paper-input>` element, but that doesn't affect the font-size of the nested `<input>` element.

**Comment by benjyblack** [comment]
Ah, use this instead `--paper-input-container-input`.

**Comment by cdata** [comment]
This looks resolved. Please re-open if the proposed solution does not work for you!
