### ISSUE TITLE
paper-dropdown-menu-light has no focus underline if no-label-float

### ISSUE THREAD

**Issue by mgiuffrida** [PolymerElements/paper-dropdown-menu#181]
The underline does not turn solid blue on focus or tap if no-label-float is on.

```
<paper-dropdown-menu-light no-label-float>
  <paper-listbox selected="0" class="dropdown-content">
    <paper-item>Foo</paper-item>
    ..
```

repro: https://jsfiddle.net/9t879aoe/

Possibly related to #179.

**Comment by mgiuffrida** [comment]
@notwaldorf friendly ping. Would be nice to get a fix for this, but either way a new release would be much appreciated :-)

**Comment by notwaldorf** [comment]
I done did a release, will take a look at this today

**Comment by notwaldorf** [comment]
Update: only repro in the shadow dom

**Comment by mgiuffrida** [comment]
Please re-open: there's still no focus underline if the label is set to `''`.

You haven't noticed this because the `<label hidden$="[[!label]]">` doesn't set `|hidden$|` until `|label|` is not `undefined`, and it starts `undefined`. If you set the label programmatically and then set it to `''`, the `label` hides completely (taking the underline/border with it).

https://jsfiddle.net/7u9bd49p/

**Comment by notwaldorf** [comment]
@mgiuffrida isn't that technically https://github.com/PolymerElements/paper-dropdown-menu/issues/190?

**Comment by mgiuffrida** [comment]
@notwaldorf No?
