### ISSUE TITLE
Keyboard input appears to no longer be working

### ISSUE THREAD

**Issue by tjsavage** [PolymerElements/paper-dropdown-menu#187]
### Description

Keyboard input appears to no longer work.

### Expected outcome

To be able to tab to a paper-dropdown-menu and then use arrow keys and enter to navigate and select.

### Actual outcome

Using arrow keys appears not to work.

### Live Demo

http://polymerlabs.github.io/element-demos-viewer/#/paper-dropdown-menu

### Steps to reproduce

1. Tab to a dropdown menu
2. Press <enter> to open it up
3. Try to use arrow keys to change the selection

Expected: that you can change the selection
Actual: Can't change selection

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [?] Edge
- [?] IE 11
- [?] IE 10

**Comment by valdrinkoshi** [comment]
This is caused by `iron-dropdown-scroll-manager` which calls `event.preventDefault()` in order to avoid scroll events (regression introduced by https://github.com/PolymerElements/iron-dropdown/pull/93).
