### ISSUE TITLE
Item label being shown instead of it content on repeated item

### ISSUE THREAD

**Issue by FdezI** [PolymerElements/paper-dropdown-menu#19]
If I use something like:

```html
<paper-dropdown-menu label="Choose an item" selectedItemLabel="{{mybind}}">
  <paper-menu class="dropdown-content">
    <template is="dom-repeat" items="[[items]]">
      <paper-item label="[[item.id]]">[[item.text]]</paper-item>
    </template>
  </paper-menu>
</paper-dropdown-menu>
```

once selected the item, instead of showing it, it shows it item's label (in this case, the item.id value). It behaves like that for every item in the repeat template but the first one.

**Comment by dballesteros7** [comment]
+1 In our use case we use the label as the ID of the item in an ng-repeat (using Angular) while the content is the display property.

**Comment by notwaldorf** [comment]
This is how `paper-dropdown-menu` works -- if there's a `label` property, it will be used as the display. If you want to fix this, you need to not set `label` in the data binding for `paper-item`.

If you think there's still a problem, please reopen with a jsbin with reproducible steps
