### ISSUE TITLE
paper-dropdown-menu-light collapses after deselection

### ISSUE THREAD

**Issue by mgiuffrida** [PolymerElements/paper-dropdown-menu#190]
Fiddle: https://jsfiddle.net/mgiuffrida/ug56pybu/

After selecting a value, deselecting a value causes the dropdown menu button to collapse. Doesn't seem to matter whether it has a label or no-label-float set.

**Comment by markus1978** [comment]
I had/have the same issue. Here is what I found: paper-dropdown-menu-light uses `<div id="input" tabindex="-1">&nbsp;</div>` to render the selected item label. If the selection is changed to no selection, this div's content is changed to `""` and not to `"&nbsp;"`. As a result the div's height is 0px and the whole component is displayed incorrectly. 

If you replace paper-dropdown-menu-light's `_valueChanged` function with
```javascript
_valueChanged: function() {
  // Only update if it's actually different.
  if (this.$.input && this.$.input.textContent !== this.value) {
    this.$.input.textContent = this.value;
    // insert &nbsp; if the value is empty string to enforce correct rendering
    if (this.value == "") {
      this.$.input.innerHTML = "&nbsp;";
    }
  }
  this._setHasContent(!!this.value);
},
```

this issue disappears.
