### ISSUE TITLE
Dropdown displays warnings when clicked

### ISSUE THREAD

**Issue by kreinholt** [PolymerElements/paper-dropdown-menu#249]
### Description

When the dropdown is clicked or an item is selected with DevTools open, 3 warnings are displayed stating KeyframeEffect is not defined.

### Expected outcome

No warning messages
### Actual outcome

3 warning messages
### Live Demo

https://www.webcomponents.org/element/PolymerElements/paper-dropdown-menu
### Steps to reproduce
1. Goto https://www.webcomponents.org/element/PolymerElements/paper-dropdown-menu
2. Open Dev Tools
3. Click 'brontosaurus'

### Browsers Affected

- [X] Chrome
- [X] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by joostdebruijn** [comment]
For others with the same issue: updating to neon-animation@2.1.0 causes this warning tobecome an error causing the paper-dropdown-menu element to stop working. To prevent that, pin neon-animation to 2.0.2 in your Bower-file.

**Comment by notwaldorf** [comment]
cc @e111077
