### ISSUE TITLE
Why selected-item-changed is fired two time ?

### ISSUE THREAD

**Issue by rokity** [PolymerElements/paper-dropdown-menu#259]
Watch this stupid example:
```html
<paper-dropdown-menu id="object" label="Dinosaurs" on-selected-item-changed="change">
      <paper-listbox slot="dropdown-content" selected="{{selected}}">
          <slot></slot>
      </paper-listbox>
    </paper-dropdown-menu>
<script>
    class DropdownInput extends Polymer.Element {
      static get is() { return 'dropdown-input'; }   
      change()
        {   
             console.log('change');    
        }
          }
    window.customElements.define(DropdownInput.is, DropdownInput);
  </script>

```
Why `selecte-item-changed` is called two time?

**Comment by stat92** [comment]
paper-dropdown-menu listens for iron-select and iron-deselect events.  When you click on an item paper-listbox fires firstly iron-deselect then iron-select. On deselect paper-dropdown-menu [drops](https://github.com/PolymerElements/paper-dropdown-menu/blob/master/paper-dropdown-menu.html#L346) own selected-item property and then on select it [resets](https://github.com/PolymerElements/paper-dropdown-menu/blob/master/paper-dropdown-menu.html#L355) for an item you've choosen.

It seems dropping isn't needed here. Possibly it's useful for multi selection when user can deselect an item. If it is we can add `if` condition `this.contentElement.multi === false` to prevent dropping.
