### ISSUE TITLE
paper-menu dropdown not triggered from mobile

### ISSUE THREAD

**Issue by kungufli** [PolymerElements/paper-dropdown-menu#28]
On mobile the `paper-menu` dropdown will not open when you tap on any point of the `paper-dropdown-menu`, as happens when you click from desktop. The menu will open only when you tap the dropdown icon on the right of the text.

**Comment by addyosmani** [comment]
Tested on Chrome beta / Android. I'm seeing every other tap on the menu not causing the dropdown to be triggered. It's somewhat sporadic. My current repro there is:

* Tap the dropdown to expand
* Attempt to tap again
* It will take a few times to display the dropdown again. If it does display on the second tap, try a third.

**Comment by kungufli** [comment]
Probably related to https://github.com/PolymerElements/paper-menu-button/issues/13

**Comment by alexandrubichis** [comment]
+1

**Comment by fiws** [comment]
Experiencing the same issue. +1

**Comment by MmariDeusdedit** [comment]
I realized that by tapping below the menu icon the menu does drop down otherwise the same issue persists!

**Comment by kungufli** [comment]
Seems fixed by some change in https://github.com/PolymerElements/iron-overlay-behavior.
