### ISSUE TITLE
Pre-select item on <paper-dropdown-menu> based on <paper-menu>'s selected attribute

### ISSUE THREAD

**Issue by zenorocha** [PolymerElements/paper-dropdown-menu#3]
I was trying the new version (which is great btw) and realized that `<paper-dropdown-menu>` doesn't pre-select an item based on this children `<paper-menu selected="1">`. 

IMO the expected behavior was to have `<paper-item>`'s second element selected, instead I have to click and select again:

![bug](https://cloud.githubusercontent.com/assets/398893/9125170/9f1e0482-3c52-11e5-8730-61775416a932.gif)

Here's the code to replicate that behavior:

```html
<!DOCTYPE html>
<html>
<head>
	<script src="bower_components/webcomponentsjs/webcomponents-lite.js"></script>

	<link rel="import" href="bower_components/paper-dropdown-menu/paper-dropdown-menu.html">
	<link rel="import" href="bower_components/paper-menu/paper-menu.html">
	<link rel="import" href="bower_components/paper-item/paper-item.html">
</head>
<body>
	<paper-dropdown-menu label="Dropdown">
		<paper-menu selected="1" class="dropdown-content">
			<paper-item>Option A</paper-item>
			<paper-item>Option B</paper-item>
			<paper-item>Option C</paper-item>
		</paper-menu>
	</paper-dropdown-menu>
</body>
</html>
```

Thanks again for putting together this new version :)

**Comment by cdata** [comment]
This sounds like a good idea to me :) thanks for reporting.

**Comment by miztroh** [comment]
Yes, please!

**Comment by kayur** [comment]
Is this intended behavior? Just wondering if this is a bug rather than an enhancement, since the previous version of paper-dropdown-menu did pre-select the item.

**Comment by srikanth2961** [comment]
Yes, this used to work in earlier versions of Polymer and should be considered as bug. Just stating this as per my assumption of bugs > enhancement.

**Comment by cdata** [comment]
Sorry, you guys are correct. I'm not sure why I added `enhancement`.

**Comment by danielbeyzade** [comment]
Ahhh this has been driving me crazy - I am glad I found out that its a known issue and a fix is on the way :+1: Thanks cdata, any idea when this will be pushed to master?

**Comment by Compufreak345** [comment]
+1

**Comment by vlad-doru** [comment]
+1
