### ISSUE TITLE
paper-dropdown-menu never show selected value on IE and Edge

### ISSUE THREAD

**Issue by kungufli** [PolymerElements/paper-dropdown-menu#31]
The `paper-dropdown-menu` never show the selected value on Internet Explorer 11 and Edge. The problem is present also in the demo page of the element: https://elements.polymer-project.org/elements/paper-dropdown-menu?view=demo:demo/index.html.

**Comment by cnbuff410** [comment]
+1. And the default style is basically broken.

**Comment by Mikanoshi** [comment]
"Production ready"
![_](https://cloud.githubusercontent.com/assets/5113439/9701082/1fc51348-5434-11e5-87b2-d892d6e5c03f.jpg)

**Comment by kungufli** [comment]
@Mikanoshi 
```
paper-menu-button {
    width: 100%;
}
```
doesn't fix the problem for me.

**Comment by Mikanoshi** [comment]
@kungufli Try to set paper-dropdown-menu width too (px or %, works either way).

**Comment by kungufli** [comment]
@Mikanoshi unfortunately this doesn't fix the problem too, nor in IE11 nor in Edge.

**Comment by Mikanoshi** [comment]
@kungufli Check all the styles I use, tested in IE11 and it works:
http://www.cyberdomain.ru/#/reg

**Comment by kungufli** [comment]
@Mikanoshi can you tell me which version of `Polymer` and `WebComponents` are you using, please?

**Comment by Mikanoshi** [comment]
@kungufli Latest:
http://www.cyberdomain.ru/polymer/bower.json

**Comment by kungufli** [comment]
@notwaldorf `paper-dropdown-menu` is still broken on IE for me. I have dropdowns in `paper-header-panel`, `paper-toolbar` and `paper-dialog` and no one is working fine, maybe https://github.com/PolymerElements/paper-dropdown-menu/pull/50 fixes the problem only when the dorpdown is not inside other elements? Please reopen, thanks.

**Comment by kungufli** [comment]
@notwaldorf I just found that the problem persist on IE in all cases where the dropdown don't have an explicit width. Setting a specific width on the element solve the problem, but this is not useful when you use the dropdown in any flexible layout, where you probably want to take advantage of the auto-resize functionality. Please reopen this issue. Thanks.

**Comment by miztroh** [comment]
@notwaldorf I've also had the issue in IE when using paper-dropdown-menu inside of neon-animated-pages which itself is inside of a neon animated page.  The input line displays fine, but the dropdown was only a couple pixels in width.  I ended up having to do something like this:

```
paper-dropdown-menu {
	--paper-menu-button-dropdown: {
		min-width: 56px;
	};
}
```

**Comment by Ermish** [comment]
+1 same issue here. 
Tried in IE11 and Edge for dropdown version 1.1.0.

**Comment by srikkbhat** [comment]
I have the same issue. Goto www.oostnet.com on ie11 or edge. the `paper-dropdown-menu` in the toolbar shows the dropdown trigger only.
