### ISSUE TITLE
paper-dropdown-menu cannot be used inside a form

### ISSUE THREAD

**Issue by notwaldorf** [PolymerElements/paper-dropdown-menu#32]
Originally opened in https://github.com/PolymerElements/iron-form/issues/49, but actually lives.

**Comment by atoy40** [comment]
May be you the iron-form-element-behavior can be implemented at a lower-level ? for example iron-select ?
Anthony.

**Comment by atoy40** [comment]
Just a simple trick to go arround:

```html
<paper-dropdown-menu label="Hard-drive">
      <paper-menu class="dropdown-content" attr-for-selected="value" selected="{{disk}}">
            <paper-item value="debian8">Linux Debian 8.0</paper-item>
            <paper-item value="debian7">Linux Ubuntu 15.04</paper-item>
      </paper-menu>
</paper-dropdown-menu>
<input type="hidden" name="disk" value="{{disk}}">
```

and you'll get a disk property in form.serialize();

**Comment by oathcomrade** [comment]
There is a behavior for that: [IronFormElementBehavior](https://github.com/PolymerElements/iron-form-element-behavior).

**Comment by atoy40** [comment]
@oathcomrade , we all know there is a behavior to "implement", that's the goal of this issue... the trick is just a workaround until the behavior is implemented in the dropdown-menu.
Anthony.

**Comment by oathcomrade** [comment]
I created a [pull request](https://github.com/oathcomrade/paper-dropdown-menu/pull/1) which should solve this particular problem.

**Comment by srikkbhat** [comment]
paper-dropdown-menu has a paper-input inside it. paper-input is capable of working with iron-form. The simple solution would be for paper-dropdown-menu to accept 'name' as a parameter and pass it to paper-input inside it. It would be great to accept a 'required' attribute and pass it on the paper-input so that we can mark this as required.
