### ISSUE TITLE
All content is horizontal-align right

### ISSUE THREAD

**Issue by dplassgit** [PolymerElements/paper-dropdown-menu#35]
After resizing, all content is right-aligned, which is non-optimal.

**Comment by johnheroy** [comment]
Looks like the element's inner <paper-menu-button> has a fixed value of 'right' for the horizontal-align attribute: https://github.com/PolymerElements/paper-dropdown-menu/blob/master/paper-dropdown-menu.html#L129

**Comment by tjsavage** [comment]
Perhaps could make this configurable?

**Comment by cdata** [comment]
`horizontal-align` could definitely be made configurable, although the OP is describing what sounds like a bug that occurs upon resize. @dplassgit could you give us some screenshots of what is happening?

**Comment by bendavis78** [comment]
Here's a [jsbin](http://jsbin.com/toloce/edit?html,output) that demonstrates the issue.

**Comment by chunkzer** [comment]
Might be far from a real solution but you can style the dropdown to be the same width as the button no problem. 

Establishing a default min-width of paper-items to be equal to the width of the dropdown button should suffice no?

Here's a demonstration using the same jsbin @bendavis78 put forward

**Comment by cdata** [comment]
This is now configurable for this element, so I am going to close this for now. Please re-open if you think there is still a problem!
