### ISSUE TITLE
Strange overlay behavior in Mobile Safari

### ISSUE THREAD

**Issue by oathcomrade** [PolymerElements/paper-dropdown-menu#37]
If a paper-dropdown-menu element is inside a paper-dialog element and dropdown-menu gets opened, it creates an overlay over everything. That is in mobile safari. In chrome and normal safari, it works fine.

**Comment by oathcomrade** [comment]
This issue can be closed, it was a bug in the flex behavior in paper-dialog.

**Comment by notwaldorf** [comment]
Apparently it's been fixed!
