### ISSUE TITLE
Remove iron-icons import

### ISSUE THREAD

**Issue by oathcomrade** [PolymerElements/paper-dropdown-menu#38]
I noted that this element imports the full iron-icons set for the arrow-drop-down icon. As I watch [polycast](https://www.youtube.com/watch?v=tjmRUgUca1g&list=PLOU2XLYxmsII5c3Mgw6fNYCzaWrsM3sMN&index=3), this is bad for the performance. Maybe the iron-icons import should be removed for that reason.

**Comment by kungufli** [comment]
+1 on that, no one want to load 60+kB just for the little icon of the dropdown.

**Comment by leogr** [comment]
:+1:

**Comment by oathcomrade** [comment]
[Pull request](https://github.com/PolymerElements/paper-dropdown-menu/pull/40) to proposed change.

**Comment by leodido** [comment]
:+1:

**Comment by notwaldorf** [comment]
I think we should use poly-icon for this. I'll take a look this week.

**Comment by ebidel** [comment]
@notwaldorf just noticed this myself for the IO app. We've created a custom icon set, but are also using paper-dropdown-menu, which brings in the default icon set.

What about doing the same as paper-tabs? It created a custom icon set for the two icons it uses:
https://github.com/PolymerElements/paper-tabs/blob/master/paper-tabs-icons.html. We could do the same for `arrow-drop-down`.

**Comment by notwaldorf** [comment]
@ebidel I was going to use `poly-icon` and do this, but if you want to send a PR, I wouldn't mind one bit!

**Comment by ebidel** [comment]
PR posted. :boom: diggity
