### ISSUE TITLE
Make it validatable

### ISSUE THREAD

**Issue by zenorocha** [PolymerElements/paper-dropdown-menu#4]
One of the use cases for a dropdown is to use it inside of a `<form>`.

Would be awesome if we could include attributes such as `error-message`, `required`, etc, and methods like `validate()` as seen on `<paper-input>`. 

What do you think?

**Comment by cdata** [comment]
Sounds good to me :+1:

**Comment by Sinjins** [comment]
+1 - Was just going to suggest adding a paper-dropdown-behavior similar to how paper-input uses it's behaviors

**Comment by miztroh** [comment]
@cdata Status?

**Comment by Gwalks91** [comment]
Any updates on this?

**Comment by bpinney** [comment]
+1

**Comment by leodido** [comment]
:+1:

**Comment by marcelmiguel** [comment]
+1

**Comment by bpinney** [comment]
Does https://github.com/PolymerElements/paper-dropdown-menu/pull/57 satisfy this issue?

**Comment by notwaldorf** [comment]
Yes, this has already been fixed in #57

**Comment by fabio-mocci** [comment]
Hello, it seems error-message wasn't implemented.  Is there any reason?

**Comment by bpinney** [comment]
@fabio-mocci, proposed PR https://github.com/PolymerElements/paper-dropdown-menu/pull/68 addresses this

**Comment by fabio-mocci** [comment]
Thank you, @bpinney !
