### ISSUE TITLE
paper-dropdown-menu + paper-dialog clips the menu

### ISSUE THREAD

**Issue by ktiedt** [PolymerElements/paper-dropdown-menu#43]
A paper-dropdown-menu inside a dialog will get clipped and be not fully accessible inside a dialog.

**Comment by lkovaleva** [comment]
FYI - adding `overflow: visible;` to the paper-dialog works around this

**Comment by ktiedt** [comment]
Yes, but that is more of a band-aid than a fix I believe.

**Comment by lkovaleva** [comment]
I totally agree, was just pointing out as a quick workaround fix for whoever might stumble into here :)

**Comment by kungufli** [comment]
Hit this problem too. @lkovaleva thanks for the workaround, works perfectly for me.

**Comment by cdata** [comment]
So for the time being, I'm not sure if there is a better alternative to defaulting `paper-dialog` to have a default overflow of `visible`. Any alternative suggestions?

**Comment by notwaldorf** [comment]
Fixed in https://github.com/PolymerElements/paper-dialog-behavior/pull/30

**Comment by kungufli** [comment]
Thank you.
