### ISSUE TITLE
paper-dropdown-menu wrongly sized in the drawer of a paper-drawer-panel (and other oddities)

### ISSUE THREAD

**Issue by kungufli** [PolymerElements/paper-dropdown-menu#46]
When a `paper-dropdown-menu` is inside a `drawer` of a `paper-drawer-panel` in the `narrow` state and you try to use the dropdown by tap in mobile mode, strange things will happens.

Firstly, the dropdown will open only when you tap on a specific area of the item:

![dropdown_drawer](https://cloud.githubusercontent.com/assets/12832388/10042932/3187e7fe-61ef-11e5-8ee2-098d62c301d8.gif)

You can also notice from the above gif that the dropdown is sized and positioned incorrectly.
Also, I noticed this strange behavior that occur when you resize the screen and that hopefully can be useful to understand the erroneous sizing of the dropdown:

![dropdown_drawer_1](https://cloud.githubusercontent.com/assets/12832388/10042968/76395f0e-61ef-11e5-9ed2-e6130f72bc40.gif)

**Comment by kungufli** [comment]
The first problem ( the dropdown will open only when you tap on a specific area of the item) seems fixed by some change in https://github.com/PolymerElements/iron-overlay-behavior.
The problem related to the sizing is still there.

**Comment by emersonbottero** [comment]
Hi @kungufli.
Do you found a workaround for the second problem. I'm struggling to solve it.

**Comment by kungufli** [comment]
@emersonbottero for the sizing problem I found a workaround (that also solve https://github.com/PolymerElements/paper-dropdown-menu/issues/27): you have to modify the source code of the `paper-dropdown-menu` element changing the `horizontal-align="right"` of the inner `paper-menu-button` to `horizontal-align="left"`.

**Comment by emersonbottero** [comment]
Thanks

**Comment by cdata** [comment]
Hi, thanks for reporting this! I'm going to close it because I believe that it is a dupe of https://github.com/PolymerElements/iron-fit-behavior/issues/33. Please re-open if you think the problem is different!
