### ISSUE TITLE
Removes scrollbar from main window

### ISSUE THREAD

**Issue by srikkbhat** [PolymerElements/paper-dropdown-menu#56]
I use firefox 40 and chrome 45. The issue exists in both the browsers. The demo page for paper-dropdown-menu can be used to recreate the issue. When the drop down is opened, the scroll bar on the main window disappears.

https://elements.polymer-project.org/elements/paper-dropdown-menu?view=demo

**Comment by srikkbhat** [comment]
This seems to be isolated issue with the demo site. I used this element in my website and it does not have the problem. So I am closing this.

**Comment by ianbitts** [comment]
I am having this same problem with my project, where the scrollbar is removed when the paper-dropdown-menu is opened. Can you elaborate on how you used the element in your website?

**Comment by srikkbhat** [comment]
I did not do anything special. I just used it as per the spec and it worked. If you think there is an issue then  you can create one with sample code and screen shots.

**Comment by freshp86** [comment]
I am noticing this too. "overflow: hidden" is attached to <body> while the dropdown menu is open, which explains why the scrollbar is disappearing.
