### ISSUE TITLE
First menu item is automatically selected

### ISSUE THREAD

**Issue by maria-le** [PolymerElements/paper-dropdown-menu#58]
Sometimes we don't want any item selected when the dropdown button is clicked and the dropdown menu is opened.

Right now, the first menu item is automatically selected when the menu is opened.

**Please make the default NO selected item when the menu is opened.**

**Comment by morficus** [comment]
Doesn't this depend on your data? The behavior your describe is exactlly how a plain "old fashion" `<select>` element works.

I think you could solve this by having the first item in your list be blank.

**Comment by cdata** [comment]
Can you please provide a reduced test case to demonstrate the problem and then re-open?

For more details, please check out our [contributing guidelines](https://github.com/PolymerElements/paper-dropdown-menu/blob/master/CONTRIBUTING.md#filing-issues).

**Comment by lastmjs** [comment]
@maria-le Did you solve this? I've got the same problem.
