### ISSUE TITLE
Setting horizontal alignment of iron-dropdown

### ISSUE THREAD

**Issue by dominik0711** [PolymerElements/paper-dropdown-menu#6]
By default the attribute `horizontal-align` is set to **right** and `vertical-align` is set to **top**. 

Is there a reason why the attributes `horizontal-align` and `vertical-align` are not exposed to be set through `paper-dropdown-menu`?

![dropdown](https://cloud.githubusercontent.com/assets/1011188/9139277/963872b2-3d29-11e5-8fb5-9acd91548efa.gif)

See: http://jsbin.com/sawutixafu/edit?html,output

**Comment by cdata** [comment]
I will need to consult the designers about this, but it seems like a good thing to support.

**Comment by dominik0711** [comment]
The alignment of the dropdown-menu should be customizable like in version **0.5**. See also [Google Material Design](https://www.google.com/design/spec/components/menus.html#menus-simple-menus) for further examples.

**Comment by bpinney** [comment]
Any update on this?

**Comment by pinkhominid** [comment]
Also, please consider `horizontal-offset` and `vertical-offset` to complete the set.
