### ISSUE TITLE
possibility to disable or change the focus when the dropdown open?

### ISSUE THREAD

**Issue by djanix** [PolymerElements/paper-dropdown-menu#60]
Example: if we want to reproduce something like this: https://twitter.github.io/typeahead.js/examples/

Right now, we can't keep the dropdown open while typing in another input. Maybe we could choose on wich input put the focus on when the dropdown is opening.

**Comment by cdata** [comment]
My two cents: we need to implement type-ahead as a separate element. I'm going to move this issue to `paper-elements`.

**Comment by cdata** [comment]
This issue was moved to PolymerElements/paper-elements#68
