### ISSUE TITLE
Invalid state appears with no reason 

### ISSUE THREAD

**Issue by summers173** [PolymerElements/paper-dropdown-menu#63]
On "_release": "1.0.5", my code broke and now all the paper-dropdown-menu appear with the invalid state colors.

Seaching for the code I found:

        <paper-ripple></paper-ripple>
        <paper-input
          invalid="[[invalid]]"

but there are no binding to that 'invalid' variable, maybe that's the issue.

Regards

**Comment by miztroh** [comment]
I can't confirm this issue since the 1.05 release.  Can you provide a repro?

**Comment by cdata** [comment]
Hi, I'm going to close this for now. Please re-open if you have a reduced test case that demonstrates the issue.

For more details, please check out our [contributing guidelines](https://github.com/PolymerElements/paper-dropdown-menu/blob/master/CONTRIBUTING.md).
