### ISSUE TITLE
'selected' attribute doesn't appear in the documentation

### ISSUE THREAD

**Issue by CSEMike** [PolymerElements/paper-dropdown-menu#66]
In the paper-dropdown-menu documentation, there's an example with a pre-selected value using the 'selected' attribute.
  https://github.com/PolymerElements/paper-dropdown-menu/blob/master/demo/index.html

But, the 'selected' attribute doesn't appear on the actual documentation page.
  https://elements.polymer-project.org/elements/paper-dropdown-menu

**Comment by morficus** [comment]
If you are referring to [this](https://github.com/PolymerElements/paper-dropdown-menu/blob/master/demo/index.html#L78) example, it is the `paper-menu` element that has a `selected` attribute, not the `paper-dropdown-menu` element.

**Comment by cdata** [comment]
Hi, this is documented where it is implemented https://github.com/PolymerElements/iron-selector/blob/master/iron-selectable.html#L57-L64. Also, yes, the property is a member of the `paper-menu`, not the `paper-dropdown-menu`.
