### ISSUE TITLE
Make value the same value as the selected value not the label.

### ISSUE THREAD

**Issue by Lindstrom1989** [PolymerElements/paper-dropdown-menu#67]
Having the selected childs value as the dropdown value like a `<select>` tag makes more sense, as the label is just for describing the selected value. For example the following dropdown should return the selected items value but instead returns the label.

```
<paper-dropdown-menu label="Subject" value="{{subject}}">
    <paper-menu class="dropdown-content">
        <paper-item value="article">A new Article</paper-item>
        <paper-item value="case">Make a case</paper-item>
        <paper-item value="question">General question</paper-item>
    </paper-menu>
</paper-dropdown-menu>
```

Using label and value attributes on a ```<paper-item>``` has no affect to paper-dropdown-menu.

**Comment by marcelmiguel** [comment]
Even with attr-for-selected="value" or attrForSelected="value" does not work.

The next example works:
```html
<paper-dropdown-menu label="{{label}}" selected-item="{{selectedItem}}" selected-item-label="{{selected}}" required>
  <paper-menu class="dropdown-content" selected="{{selectedvalue}}" attr-for-selected="value">
    <template is="dom-repeat" items="{{items}}" as="item">
      <paper-item value="[[item.id]]">[[item.description]]</paper-item>
    </template>
  </paper-menu>
</paper-dropdown-menu>
<input is="iron-input" name="[[name]]" id="[[id]]" type="hidden" value="[[selectedItem.value]]">
```
But then we cannot use "required" on paper-dropdown.menu, and does not work on a form !

**Comment by Lindstrom1989** [comment]
@marcelmiguel I'm confused is this adding onto what I'm saying or a solution?

**Comment by marcelmiguel** [comment]
@Lindstrom1989 Both.
I agree there is the "value" problem with "paper-dropdown-menu" . 
The example given is a temporary solution.

**Comment by Lindstrom1989** [comment]
@marcelmiguel Ahh I see yes does feel a bit odd. :)

**Comment by Lindstrom1989** [comment]
@marcelmiguel Great temporary solution btw

**Comment by cdata** [comment]
Hey guys, can you update this request with a specific design proposal for changing `paper-dropdown-menu`? I would love to see a concise example of what we have and how it should change. I'm going to close the issue for now, but please re-open the issue when you update it!

**Comment by H3dz** [comment]
@Lindstrom1989 Do you know if this was resolved?
With an iron-form, I can't find a way to use the value attribute instead of the selected item label.

**Comment by Lindstrom1989** [comment]
I'm not sure this was awhile ago I have since been more involved with angular 2 which is kickass at forms ;)
From memory I used @marcelmiguel temporary fix

**Comment by mikabenali** [comment]
Hi @Lindstrom1989 

Have you an exemple with Angular 2 ?
I have an error message when trying to add "formControlName" attribute to paper-drop-down-menu.

`Cannot set property value of #<paper-dropdown-menu> which has only a getter`
