### ISSUE TITLE
Optgroup analogy not present

### ISSUE THREAD

**Issue by prateekbh** [PolymerElements/paper-dropdown-menu#69]
We should enable optgroup analogy in paper-dropdown-menu

**Comment by prateekbh** [comment]
or may be in iron-dropdown

**Comment by cdata** [comment]
I think this behavior is already supported. Any content is allowed in a `paper-dropdown-menu`. It is not tightly coupled to any specific component. If you can provide a test case that shows it is not possible, please re-open the issue!
