### ISSUE TITLE
paper-dropdown-menu not aligned with a paper-input

### ISSUE THREAD

**Issue by dballesteros7** [PolymerElements/paper-dropdown-menu#7]
When putting a paper-input and a paper-dropdown-menu together in a vertical layout, the labels do not align. I think this is a common setup for these elements and I would expect the labels to align vertically, e.g.

![example](https://cloud.githubusercontent.com/assets/1774523/9133975/45de45e0-3d00-11e5-9392-3e8ebb7a6ee4.png)

```HTML
<div class="layout vertical">
  <paper-input label="Input!"></paper-input>
  <paper-dropdown-menu label="Dropdown!">
    <paper-menu>
      <paper-item>A</paper-item>
      <paper-item>B</paper-item>
      <paper-item>C</paper-item>
    </paper-menu>
  </paper-dropdown-menu>
</div>
```

This caused by the [paper-menu-button padding](https://github.com/PolymerElements/paper-menu-button/blob/master/paper-menu-button.html#L66), but I think this should not be present in the paper-dropdown-menu.

**Comment by zenorocha** [comment]
+1, I noticed that too.

**Comment by grokys** [comment]
+1 - the `<paper-dropdown-menu>` element itself is correctly justified but the `<paper-menu-button>` inside seems to be left-aligned with an 8px padding.

**Comment by cdata** [comment]
Nice catch, thanks for reporting this. I will get a fix in.

**Comment by realiztiK** [comment]
Top margin seems off.
Might be a bit hacky but, this worked for me:

<dom-module id="paper-dropdown-menu">
  <style>
    :host {
      display: inline-block;
      position: relative;
      text-align: left;
      cursor: pointer;
      margin-top: -8px;

...
}

**Comment by grokys** [comment]
This still doesn't appear to be fixed in 1.0.2 for me.

**Comment by lkovaleva** [comment]
As a side note - I was adding `padding: 0;` to the paper-menu-button, but that has a weird side-effect on the ripple and makes it appear smaller, so it seems I must then also add `margin: -8px;` to the paper-ripple within to actually make it all look okay.

**Comment by gazal-k** [comment]
This works for me.

```css
:root {
  --paper-dropdown-menu-button: {
      padding: 0;
    };

    --paper-dropdown-menu-ripple: {
      left: 0;
      bottom: 0;
    };
}
```

**Comment by grokys** [comment]
Any chance of getting this fixed? Do you need a PR for it?

**Comment by notwaldorf** [comment]
On it! I think it just fell off the radar. I'll have a PR ready in a bit.

**Comment by grokys** [comment]
Thanks @notwaldorf !
