### ISSUE TITLE
Shorthand syntax

### ISSUE THREAD

**Issue by BLamy** [PolymerElements/paper-dropdown-menu#74]
The current syntax for creating a simple menu is a little bit verbose, especially if you have several menus on one page. 

A shorthand syntax would be nice for when I want to construct a simple menu. 
`<paper-dropdown-menu selected="foo" options='["foo","bar"]'></paper-dropdown-menu>`

**Comment by cdata** [comment]
This sounds like it would make a great community-contributed element! Please let us know if you make one :)
