### ISSUE TITLE
On Safari two clicks are needed to select an item from the menu

### ISSUE THREAD

**Issue by kungufli** [PolymerElements/paper-dropdown-menu#76]
On Safari almost all times you click on an item in the menu of a `paper-dropdown-menu` the item get the focus but is not selected and the menu remains opened, then you have to click another time on the focused item to effectively select it (and at this point the menu also closes). On all other browsers I tested (Chrome, Firefox, Edge and IE) when you click on an item it is selected and the menu closes automatically.

**Comment by cdata** [comment]
Hi, I believe that this is fixed. Please re-open the issue if it is not fixed for you!

**Comment by kungufli** [comment]
@cdata confirmed, it's ok now. Many thanks!
