### ISSUE TITLE
Missing errorMessage property of the paper-input

### ISSUE THREAD

**Issue by govis** [PolymerElements/paper-dropdown-menu#78]
Along with the the invalid property (already in place) paper-dropdown-menu should expose an errorMessage property and bind it to the underlying paper-input's errorMessage to make it consistent with other elements and available for custom validation.

**Comment by bpinney** [comment]
Proposed PR https://github.com/PolymerElements/paper-dropdown-menu/pull/68 addresses this.

**Comment by Qvatra** [comment]
When error-message attribute would be available for users?

**Comment by Nick-Ewer** [comment]
Any plans for this? I've cloned the element and added in the two lines necessary to expose this functionality, but it would definitely be nice to have this as a standard feature to reduce the number of elements being used. Thanks!

**Comment by fabiomocci** [comment]
Hi Nick-Ewer, until this issue isn't done, can you put here the code of your solution?

I'm with the same necessity.

Thanks!

**Comment by Qvatra** [comment]
@Nick-Ewer, Can you maybe make a pull request then?

**Comment by bpinney** [comment]
As I stated above, proposed PR https://github.com/PolymerElements/paper-dropdown-menu/pull/68 addresses this.

**Comment by fabiomocci** [comment]
Thanks @bpinney, I just wrote now in #68.

**Comment by notwaldorf** [comment]
I just merged #68!
