### ISSUE TITLE
How to bind value to object property?

### ISSUE THREAD

**Issue by dominik0711** [PolymerElements/paper-dropdown-menu#8]
Hi.

Is there a way to bind the selected item in the paper-dropdown-menu to object property? This was the way how to do in **0.5**:

```
<paper-dropdown-menu label="{{i18n.label}}">
  <paper-dropdown class="dropdown">
    <core-menu class="menu"
               valueattr="id"
               selected="{{prj.selitem}}">
      <template repeat="{{fs in prj.list}}">
        <paper-item id="{{fs}}">{{fs | xlate}}</paper-item>
      </template>
    </core-menu>
  </paper-dropdown>
</paper-dropdown-menu>
```

With the above solution I could bind the selected item to `prj.selitem`. What is the `right` solution in **1.0**??? How do I trigger the change of `prj.selitem`? Do I have to provide a function for that in which I have to call `this.set('prj.selitem', item)` or something like this? 

Would you please provide an example or make a section in the documentation?

**Comment by azumbrunnen** [comment]
I have the same problem. You can use selected-item="{{ yourVariable }}". However, on the change event for computed bindings it will report the selected-item instead of the value. It's a pretty strange behaviour.

**Comment by klarkc** [comment]
+1

**Comment by cdata** [comment]
Hi, it should be sufficient to do the following:

```html
<paper-dropdown-menu>
  <paper-menu attr-for-selected="value" selected="{{someObject.someProperty}}">
    <template is="dom-repeat" items="{{someArray}}">
      <paper-item value$="{{item}}">{{item}}</paper-item>
    </template>
  </paper-menu>
</paper-dropdown-menu>
```

Please re-open if this does not work for you!
