### ISSUE TITLE
Wrong `value` when submitting form

### ISSUE THREAD

**Issue by morficus** [PolymerElements/paper-dropdown-menu#81]
Looking at this elements source code, I believe that having the `value` attribute ALWAYS be the same as `selectedItemLabel` leads to an unexpected behavior [[src](https://github.com/PolymerElements/paper-dropdown-menu/blob/master/paper-dropdown-menu.html#L220)], and here is why:

In order for this element to even work you MUST use `paper-menu` (ref: #24) , which has an attribute called `attrForSelected`. As indicated in the [documentation](https://elements.polymer-project.org/elements/paper-menu), this allows you to specify what attribute you want to use when asking for the selected item.

Because `paper-dropdown-menu` has a hard dependency on `paper-menu`, one would expect `paper-dropdown-menu.value` to return the same as `paper-menu.attr-for-selected`

**Comment by zmoshansky** [comment]
+1

It breaks the following use case; where one might like to get an id as the result of the selection. 
```
<paper-dropdown-menu label="Your favourite pastry">
  <paper-menu class="dropdown-content" attr-for-selected="value">
    <paper-item value=1>Croissant</paper-item>
    <paper-item value=2>Donut</paper-item>
    <paper-item value=3>Financier</paper-item>
    <paper-item value=4>Madeleine</paper-item>
  </paper-menu>
</paper-dropdown-menu>
```

**Comment by cdata** [comment]
Hi, first: thanks for all of the investigation. `paper-dropdown-menu` does not have a hard dependency on `paper-menu` or `paper-listbox`. It has a squishy :bug: dependency on an element that fires `iron-select` / `iron-deselect` events.

Can you provide a reduced test case that demonstrates `paper-dropdown-menu` submitting an unexpected value to a form, and then re-open?

For more details, here are our [contributing guidelines](https://github.com/PolymerElements/paper-dropdown-menu/blob/master/CONTRIBUTING.md).

**Comment by morficus** [comment]
Hey @cdata,

Issue #104 has a lot more details as well as a proposed solution an a matching pull request - all while following the contribution guidelines.
