### ISSUE TITLE
paper-dropdown demo errors

### ISSUE THREAD

**Issue by laicosly** [PolymerElements/paper-dropdown-menu#86]
Chrome 46, the demo does not render, with a string of errors in the console.

https://elements.polymer-project.org/elements/paper-dropdown-menu?view=demo:demo/index.html&active=paper-dropdown-menu

```
Uncaught NotSupportedError: Failed to execute 'registerElement' on 'Document': Registration failed for type 'dom-module'. A type with that name is already registered.
```

**Comment by dsschnau** [comment]
+1, Fails in Firefox as well

**Comment by cdata** [comment]
Not reproducible in the latest release. Please re-open this issue if it still occurs, with a JSBin containing a set of reproducible steps. For more details on filing issues, please refer to our [contributing guidelines](../blob/master/CONTRIBUTING.md).
