### ISSUE TITLE
`iron-overlay-closed` event bubbles up unexpectedly

### ISSUE THREAD

**Issue by morficus** [PolymerElements/paper-dropdown-menu#87]
__Use case__: when using a `<paper-dropdown-menu>` element is contained with in a `<paper-dialog>` element, the `iron-overlay-closed` listener gets triggered when the `<paper-dropdown-menu>` is closed.

__Impact__: the function registered to the listener gets triggered at unexpected times

__Demo__: https://jsbin.com/sugocaguva/edit?html,output

**Comment by kriscooke** [comment]
+1 Not sure why/whether it's supposed to bubble up... If so, then we need a more specific 'closed' event from paper-dialog. Particularly hazardous for 'closed' listeners like `form.reset()`!

**Comment by cdata** [comment]
This sounds reasonable. These events probably shouldn't bubble.

@valdrinkoshi do you have any opinions about this?

**Comment by valdrinkoshi** [comment]
Yeah it makes sense, the event shouldn't bubble. But I don't know if this should be fixed in `iron-overlay-behavior` to fire an event that doesn't bubble, or handle it in the `paper-dropdown-menu`..

**Comment by fakiolinho** [comment]
Maybe an idea would be the option to attach the event to an emitter. So if an emitter's id is provided we can understand who emits it and respond accordingly. If the emitter's id is omitted the event can be caught by everyone as usual:

```javascript
listeners: {
    'dialogID.iron-overlay-closed': '_modalClosed',
    'dropdownMenuID.iron-overlay-closed': '_menuClosed'
 },
_modalClosed: function(e) {

},
_menuClosed: function(e) {

}
 ```

So i could respond on those 2 using separate methods.

**Comment by valdrinkoshi** [comment]
related to https://github.com/PolymerElements/iron-overlay-behavior/issues/70, see [proposed solution](https://github.com/PolymerElements/iron-overlay-behavior/issues/70#issuecomment-172035455].
Changing the event to non-bubble would be a breaking change, so I'd suggest to use the proposed solutions & close this issue.

**Comment by valdrinkoshi** [comment]
Will move this issue to `paper-menu-button` as it has already 2 other events for opening/closing, and it should be the one stopping the propagation of `iron-overlay-opened/closed/canceled`

**Comment by valdrinkoshi** [comment]
This issue was moved to PolymerElements/paper-menu-button#86
