### ISSUE TITLE
Keyboard support?

### ISSUE THREAD

**Issue by eliseosoto** [PolymerElements/paper-dropdown-menu#9]
It should behave like a <select> element. That is, when I open the menu I should be able to move up/down with the up/down keys and the potential new selection should be highlighted.

**Comment by cdata** [comment]
Hi, thanks for reporting. This works, if focus is correctly forwarded to the menu after it opens. Unfortunately, right now the only way to do that is by tabbing to it once you have opened the menu. I am working on a fix for this problem.
