### ISSUE TITLE
demo looks poor due to scrollbar appearing/disappearing

### ISSUE THREAD

**Issue by davidmaxwaterman** [PolymerElements/paper-dropdown-menu#95]
1. visit : https://elements.polymer-project.org/elements/paper-dropdown-menu?view=demo:demo/index.html&active=paper-dropdown-menu
2. observe a double scrollbar
3. click on the basic menu menu
4. observe a single scrollbar, as well as a side-ways 'jitter' as the scrollbar appears/disappears.

Please consider fixing it to look better.

**Comment by MeinAccount** [comment]
This is essentially an issue of the [`IronDropdownScrollManager`](https://github.com/PolymerElements/iron-dropdown/blob/master/iron-dropdown-scroll-manager.html). [I've written a quick fix to prevent the entire page from moving to the right.](https://gist.github.com/MeinAccount/1614c4ae3edcea7d4660)

**Comment by cdata** [comment]
This is totally a problem. It may be sufficient for us to not turn off scroll for the document body (which would fix this for a lot of cases). It needs exploration.

**Comment by cdata** [comment]
This issue was moved to PolymerElements/iron-dropdown#54
