### ISSUE TITLE
API doc should show paper-listbox?

### ISSUE THREAD

**Issue by arthurevans** [PolymerElements/paper-dropdown-menu#97]
The demos appear to use the new `paper-listbox` instead of `paper-menu`, but the example in the API doc uses `paper-menu`. Are they both equally viable? Or should we be recommending people use `paper-listbox` instead?

**Comment by morficus** [comment]
I was wondering the same question.
this issues seems to be related to #24

**Comment by abdonrd** [comment]
Fixed?

**Comment by bicknellr** [comment]
Whoa, didn't notice I was assigned this; looks fixed thanks to @srikkbhat w/ #126 and should be in the docs next time we do a refresh.
